apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: app
  template:
    metadata:
      name: shipping
      labels:
        project: roboshop
        component: shipping
        tier: app
    spec:
      containers:
      - name: shipping
        image: koti0120/shipping:v1
        envFrom:
          - configMapRef:
              - name: shipping-config
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  selector:
    project: roboshop
    component: shipping
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"